# Generated by Django 5.2.5 on 2025-08-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
