# Generated by Django 5.2.5 on 2025-08-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_faq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.TextField(default='General'),
        ),
    ]
